GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Restoring states from the checkpoint path at ./ckpt250103/diffsketch_epoch=345.ckpt
Namespace(activation='silu', actnorm=True, aggregation_method='sum', attention=True, augment_noise=0, batch_size=64, break_train_epoch=False, brute_force=False, center_of_mass='interface', checkpoints='./ckpt', clip_grad=True, condition_time=True, conditioning=[], config='./testold.yml', data='../DiffSketch/CATH_slide_12time.pt', data_augmentation=True, datadir='qm9/temp', dataset='qm9', dequantization='argmax_variational', device='cuda', diffusion_loss_type='l2', diffusion_noise_precision=1e-05, diffusion_noise_schedule='polynomial_2', diffusion_steps=500, dp=True, ema_decay=0.999, enable_progress_bar=True, enable_wandb=True, exp_name='setup_sketchdiff', filter_n_atoms=None, generate_epochs=1, inv_sublayers=1, log_iterations=None, logs='./logs', lr=0.0002, model='egnn_dynamics', n_epochs=2000, n_layers=6, n_report_steps=1, n_stability_samples=1, nf=128, no_cuda=True, no_wandb=False, norm_constant=1, normalization='batch_norm', normalization_factor=1, normalize_factors=[10, 4], num_workers=0, ode_regularization=0.001, online=False, pad_data=False, probabilistic_model='diffusion', remove_h=False, resume=None, save_model=True, sin_embedding=True, start_epoch=0, tanh=False, test_epochs=20, trace='hutch', trainer_params=None, visualize_every_batch=100000000.0, wandb_entity='yangyangmiao', wandb_usr=None)
device is !!!!!!!!!  cuda:0
silu
Start training
Traceback (most recent call last):
  File "train_gvp.py", line 164, in <module>
    trainer.fit(model=ddpm,ckpt_path='./ckpt250103/diffsketch_epoch=345.ckpt')
  File "/work/lpdi/users/ymiao/Topoflowenv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "/work/lpdi/users/ymiao/Topoflowenv/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/work/lpdi/users/ymiao/Topoflowenv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/work/lpdi/users/ymiao/Topoflowenv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 955, in _run
    self._checkpoint_connector._restore_modules_and_callbacks(ckpt_path)
  File "/work/lpdi/users/ymiao/Topoflowenv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 397, in _restore_modules_and_callbacks
    self.resume_start(checkpoint_path)
  File "/work/lpdi/users/ymiao/Topoflowenv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 79, in resume_start
    loaded_checkpoint = self.trainer.strategy.load_checkpoint(checkpoint_path)
  File "/work/lpdi/users/ymiao/Topoflowenv/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 367, in load_checkpoint
    return self.checkpoint_io.load_checkpoint(checkpoint_path)
  File "/work/lpdi/users/ymiao/Topoflowenv/lib/python3.8/site-packages/lightning_fabric/plugins/io/torch_io.py", line 81, in load_checkpoint
    raise FileNotFoundError(f"Checkpoint file not found: {path}")
FileNotFoundError: Checkpoint file not found: ./ckpt250103/diffsketch_epoch=345.ckpt
